import pyautogui as pygui
import time
import selenium
size_x, size_y = pygui.size()
print(f"Tamanho da Tela", size_x, size_y)
time.sleep(3)
position_x, position_y = pygui.position()
print(f"mouse position: X > {position_x} and Y > {position_y}")

pygui.doubleClick(40, 438)
time.sleep(2)
pygui.hotkey('win', 'up')
pygui.write('https://mail.google.com/mail/u/0/#inbox')
time.sleep(2)
pygui.press('enter')
time.sleep(5)
pygui.click(68, 174)
time.sleep(2)
pygui.write('sandro.mesquita@professor.uniateneu.edu.br')
time.sleep(1)
pygui.press('tab')
pygui.press('tab')
time.sleep(1)
pygui.write('Prova de Python Automatizada')
time.sleep(1)
pygui.press('tab')
pygui.write('Segue em anexo os arquivos conforme solicitado. Ressalto que foi um robo que enviou os arquivos.')
time.sleep(1)
pygui.click(326, 669)
time.sleep(1)
pygui.write(r'C:\Users\Aluno\Desktop\grafico_download.png')
pygui.press('enter')
time.sleep(10)
pygui.click(326, 669)
time.sleep(1)
pygui.write(r'C:\Users\Aluno\PycharmProjects\pythonProject1\automacao.py')
time.sleep(1)
pygui.press('enter')
time.sleep(10)
pygui.hotkey('ctrl', 'enter')

#pygui.moveTo(108, 45, 3)
#pygui.doubleClick(108, 45)
#time.sleep(2)
#pygui.write('Jonny Paiva')
#time.sleep(2)
#pygui.hotkey('ctrl','S')
#time.sleep(2)
#pygui.hotkey('alt', 'f4')
#time.sleep(2)
#pygui.press('enter')




